on:
  workflow_call:
    inputs:
      config_file:
        required: true
        type: string
        description: 'The vertagus configuration file to use for commit tagging configuration'

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: install dependencies
        run: pip install -e "." tomli packaging pyyaml
      - name: run prod version tag
        if: ${{ startsWith( github.head_ref, 'release/' ) || startsWith( github.head_ref, 'hotfix/' ) }}
        run: vertagus create-tag -c ${{ inputs.config_file }} -s prod
      - name: run beta version tag
        if: ${{ !startsWith( github.head_ref, 'dev/' ) && !startsWith( github.head_ref, 'release/' ) && !startsWith( github.head_ref, 'hotfix/' ) }}
        run: vertagus create-tag -c ${{ inputs.config_file }} -s beta
