name: Documentation

on:
  workflow_call:
    inputs:
      dev:
        required: false
        type: boolean
        default: false
        description: 'If true, deploys to the development version of the documentation. Defaults to false.'

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[docs]"

      - name: Configure git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Show deployment context
        run: |
          echo "GitHub Event: ${{ github.event_name }}"
          echo "GitHub Ref: ${{ github.ref }}"
          echo "GitHub Head Ref: ${{ github.head_ref }}"
          echo "Repository: ${{ github.repository }}"

      - name: Build and deploy documentation
        env:
          CI: true
        run: |
          VERSION=$(vertagus show-version)
          echo "Running mike-docs.sh with dev=${{ inputs.dev }}"
          echo "Using version: $VERSION"
          if [[ "${{ inputs.dev }}" == "true" ]]; then
            echo "Deploying development documentation"
            ./scripts/mike-docs.sh deploy-dev
          else
            ./scripts/mike-docs.sh deploy "$VERSION"
          fi
