name: vertagus PR merge workflow
on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - "src/**"
      - "pyproject.toml"
      - "vertagus.toml"

jobs:
  tag-commit:
    uses: ./.github/workflows/reusable.tag-commit.yml
    with:
      config_file: "./vertagus.toml"

  publish-to-test-pypi:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://test.pypi.org/legacy/
    permissions:
      id-token: write 
    steps:
    - name: Build package
      run: |
        python3 -m pip install --upgrade build
        ls -al
        python3 -m build

    - name: Publish package distributions to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
